#!/usr/bin/perl 
use strict;
use warnings;
use CGI qw(:standard *table);
use lib '/opt/www/AT/lib';
use AT::GFX::SeqColorIndex;

my $STYLESHEET = "/gbrowse/gbrowse-cne.css";

my $CGI = CGI->new;

main();
exit;

##
## Subroutines
##

sub main
{
    # Print HTML header
    print_header(-title => "HCNE color legend",
		# -style => {-code => "body { background-color: white }" }
	);


    print h2("HCNE color legend");

    # Pring scheme selection form
    print start_form(-name => 'mainform');
    print "Show color legend for: ";
    print popup_menu(-name => 'scheme',
		     -values => ['dark', 'UCSC'],
		     -default => 'dark',
		     -labels => {dark => 'default colors', UCSC => 'UCSC colors' },
		     -onChange => 'document.mainform.submit();');   
    print end_form();
    print p();
      
    my $seq_color_index = AT::GFX::SeqColorIndex->new(scheme => $CGI->param('scheme') || 'dark');
    my $legend = $seq_color_index->get_legend();
    my $colors = $legend->{colors};
    my $names = $legend->{names};

    my @rows;

    my $i = 0;
    while($i < @$colors) {
	my @cells;
	for my $j (1..4) {
	    my $color_str = sprintf("#%02x%02x%02x", @{$colors->[$i]});
	    push @cells, td({-style => "background-color:$color_str"}, '&nbsp;&nbsp;&nbsp;');
	    push @cells, td($names->[$i]);

	    #print p({-style=>"color:$color_str"}, $names->[$i]);
	    last if(++$i == @$colors);
	}
	push @rows, Tr(@cells);
    }
    
    print table({-style => 'background-color:white'}, @rows);

    print $legend->{note}, "\n";

    # Print HTML footer
    print_footer();
}


# Print HTML header
{
    my $_printedHeader = 0;
    sub print_header
    {
	return if($_printedHeader);
	$_printedHeader = 1;
	my %args = @_;
	print $CGI->header();
	$args{-title} = "HCNE color legend" unless($args{-title});
	$args{-style}{-src} = $STYLESHEET unless($args{-style}{-src});
	print $CGI->start_html(%args), "\n\n";
	#print_navigation_bar();
	print "\n";
    }
}

# Print HTML footer
sub print_footer
{
    print $CGI->end_html;
}


sub fail 
{
    print_header();
    print(@_);
    print_footer();
    exit;
}



