/* Cast/defs.h.  Generated by configure.  */
/* Cast/defs.h.in.  Generated from configure.in by autoheader.  */

#ifndef CAST_DEFS_H
#define CAST_DEFS_H

/* Name of package */
#ifndef PACKAGE
#define PACKAGE "Cast"
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT "http://savannah.cern.ch/projects/clhep/"
#endif

/* Define to the full name of this package. */
#ifndef PACKAGE_NAME
#define PACKAGE_NAME "CLHEP Cast"
#endif

/* Define to the full name and version of this package. */
#ifndef PACKAGE_STRING
#define PACKAGE_STRING "CLHEP Cast 2.0.3.1"
#endif

/* Define to the one symbol short name of this package. */
#ifndef PACKAGE_TARNAME
#define PACKAGE_TARNAME "Cast"
#endif

/* Define to the version of this package. */
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "2.0.3.1"
#endif

/* Version number of package */
#ifndef VERSION
#define VERSION "2.0.3.1"
#endif

#endif  // CAST_DEFS_H
